import { 
  SiSpringboot, 
  SiNextdotjs, 
  SiReact, 
  SiTypescript, 
  SiPostgresql, 
  SiDocker, 
  SiRedis, 
  SiGit, 
  SiTailwindcss, 
  SiMongodb, 
  SiVercel, 
  SiGithubactions, 
  SiFigma,
  SiMysql,
  SiPostman,
  SiIntellijidea,
  SiNodedotjs,
  SiGo,
  SiKubernetes,
  SiCplusplus,
  SiElasticsearch,
  SiGrafana,
  SiDatadog,
  SiPython,
  SiHibernate,
  SiExpress,
  SiJira,
  SiJavascript,
} from "react-icons/si";
import { Cloud, Layout, Database, Server, Smartphone, Cpu, Box, GraduationCap, Shapes, Layers } from "lucide-react";
import { FaJava } from "react-icons/fa6";

export const ICON_MAP: Record<string, any> = {
  java: FaJava,
  cpp: SiCplusplus,
  javascript: SiJavascript,
  go: SiGo,
  python: SiPython,
  springboot: SiSpringboot,
  springsecurity: SiSpringboot, // Using Spring icon
  hibernate: SiHibernate,
  nodejs: SiNodedotjs,
  express: SiExpress,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  elasticsearch: SiElasticsearch,
  docker: SiDocker,
  k8s: SiKubernetes,
  grafana: SiGrafana,
  datadog: SiDatadog,
  dsa: GraduationCap,
  "system-design": Shapes,
  oop: Box,
  "os": Cpu,
  jira: SiJira,
  spring: SiSpringboot,
  nextjs: SiNextdotjs,
  react: SiReact,
  typescript: SiTypescript,
  tailwind: SiTailwindcss,
  git: SiGit,
  figma: SiFigma,
  aws: Cloud,
};

export const TECH_COLORS: Record<string, string> = {
  java: "text-[#ED8B00]",
  cpp: "text-[#00599C]",
  javascript: "text-[#F7DF1E]",
  go: "text-[#00ADD8]",
  python: "text-[#3776AB]",
  springboot: "text-[#6DB33F]",
  springsecurity: "text-[#6DB33F]",
  hibernate: "text-[#59666C]",
  nodejs: "text-[#339933]",
  express: "text-white",
  mysql: "text-[#4479A1]",
  postgresql: "text-[#4169E1]",
  mongodb: "text-[#47A248]",
  redis: "text-[#DC382D]",
  elasticsearch: "text-[#005571]",
  docker: "text-[#2496ED]",
  k8s: "text-[#326CE5]",
  grafana: "text-[#F46800]",
  datadog: "text-[#632CA6]",
  dsa: "text-purple-400",
  "system-design": "text-blue-400",
  oop: "text-emerald-400",
  "os": "text-orange-400",
  jira: "text-[#0052CC]",
  spring: "text-[#6DB33F]",
  nextjs: "text-white",
  react: "text-[#61DAFB]",
  typescript: "text-[#3178C6]",
  tailwind: "text-[#06B6D4]",
  git: "text-[#F05032]",
  figma: "text-[#F24E1E]",
  aws: "text-[#FF9900]",
};
